name:build
on:[push,pull_request]
jobs:
 build:
  runs-on:${{matrix.os}}
  strategy:
   fail-fast:false
   matrix:
    os:[windows-latest]
    build_type:[Release]
    enable_ui:[on]
    include:
     -os:windows-latest
      build_type:Release
      enable_ui:on
  steps:
  -uses:actions/checkout@v3
   with:
    submodules:'recursive'
  -name:ccache
   uses:hendrikmuhs/ccache-action@v1
   if:runner.os=='Linux'
   with:
    key:${{matrix.os}}-${{matrix.enable_ui}}
  -uses:seanmiddleditch/gha-setup-ninja@master
  -uses:ilammy/msvc-dev-cmd@v1
   if:runner.os=='Windows'
  -name:InstallDependencies
   shell:bash
   run:|
    if[["${{runner.os}}"=="Linux"]];then
     sudoapt-getupdate-qq
     sudoapt-getinstall-y\
      libx11-devlibxcursor-devlibxi-dev
    fi
  -name:GeneratingMakefiles
   shell:bash
   run:|
    if[["${{runner.os}}"=="Windows"]];then
     exportenable_ccache=off
    else
     exportenable_ccache=on
    fi
    curl-Lhttps://github.com/blueloveTH/aseprite/releases/download/v0.01/skia.zip--outputskia.zip
    7zxskia.zip
    cmake-S.-Bbuild-GNinja\
     -DCMAKE_BUILD_TYPE=${{matrix.build_type}}\
     -DENABLE_UI=${{matrix.enable_ui}}\
     -DENABLE_CCACHE=$enable_ccache\
     -DLAF_BACKEND=skia\
     -DSKIA_DIR=./skia\
     -DSKIA_LIBRARY_DIR=./skia/out/Release-x64\
     -DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib
  -name:Compiling
   shell:bash
   run:|
    cdbuild&&ninja
  -uses:actions/upload-artifact@v3
   with:
    name:aseprite
    path:|
D:/a/aseprite/aseprite/build/bin/data
D:/a/aseprite/aseprite/build/bin/aseprite.exe
